FROM node:17-slim

WORKDIR /app

COPY package.json next.config.js postcss.config.js nexus.tsconfig.json codegen.yml next-env.d.ts tailwind.config.js ./

RUN yarn install

COPY src ./src

COPY public ./public

COPY .env ./

COPY scripts ./

RUN yarn run build

CMD [ "yarn", "start:prod" ]
