- name: All
  hosts: main
  # vars_files:
  #   - group_vars/vault.yml
  roles:
    - role: "mount"
      tags: "mount"
    - role: "docker"
      tags: "docker"
    - role: "nifi"
      tags: "nifi"
    # - role: "nifi-registry"
    #   tags: "nifi-registry"
    # - { role: "postgres", tags: "postgres" }
