- name: Add crons
  ansible.builtin.cron:
    name: "{{ item.name }}"
    minute: "{{ item.minute }}"
    hour: "{{ item.hour }}"
    user: "{{ item.user }}"
    job: "{{ item.job }}"
  loop: "{{ cron }}"
