- name: Mount up device by UUID
  ansible.posix.mount:
    path: "{{ item.path }}"
    src: "UUID={{ item.uuid }}"
    fstype: "{{ item.fstype }}"
    state: present
  with_items: "{{ mount_blocks }}"
