- name: create directory for postgres
  file:
    path: "{{ work_dir }}/postgres"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_group }}"

- name: create data directory for postgres
  file:
    path: "{{ work_dir }}/postgres/data"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_group }}"

- name: add postgres docker compose
  template:
    src: docker-compose.yml.j2
    dest: "{{ work_dir }}/postgres/docker-compose.postgres.yml"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"

- name: Start postgres
  shell: "docker-compose -f {{ work_dir }}/postgres/docker-compose.postgres.yml up -d --force-recreate"
