- name: Create postgres group
  group:
    name: "{{ postgres_group }}"
    state: present

- name: Create postgres user
  user:
    name: "{{ postgres_user }}"
    group: "{{ postgres_group }}"

- name: create directory for postgres
  file:
    path: "{{ postgres_home_dir }}"
    state: directory
    owner: "{{ postgres_user }}"
    group: "{{ postgres_group }}"

- name: create data directory for postgres
  file:
    path: "{{ postgres_data_dir }}"
    state: directory
    owner: "{{ postgres_user }}"
    group: "{{ postgres_group }}"

- name: add postgres docker compose
  template:
    src: docker-compose.yml.j2
    dest: "{{ postgres_home_dir }}/docker-compose.yml"
    owner: "{{ postgres_user }}"
    group: "{{ postgres_group }}"

- name: Start postgres
  shell: "docker compose -f {{ postgres_home_dir }}/docker-compose.yml up -d --force-recreate"
