- name: Create nifi group
  group:
    name: "{{ nifi_registry_group }}"
    state: present

- name: Create nifi user
  user:
    name: "{{ nifi_registry_user }}"
    group: "{{ nifi_registry_group }}"

- name: Create directory for nifi
  file:
    path: "{{ nifi_registry_dir }}"
    state: directory
    owner: "{{ nifi_registry_user }}"
    group: "{{ nifi_registry_group }}"

- name: Create data directory for nifi registry
  file:
    path: "{{ nifi_registry_dir }}/data"
    state: directory
    owner: "{{ nifi_registry_user }}"
    group: "{{ nifi_registry_group }}"

- name: Create nifi registry internals directories
  file:
    path: "{{ nifi_registry_dir }}/data/{{ item }}"
    state: directory
    owner: "{{ nifi_registry_user }}"
    group: "{{ nifi_registry_group }}"
  loop:
    - test

- name: Add nifi registry docker compose
  template:
    src: docker-compose.yml.j2
    dest: "{{ nifi_registry_dir }}/docker-compose.yml"
    owner: "{{ nifi_registry_user }}"
    group: "{{ nifi_registry_group }}"

# - name: Check if bootstrap needed
#   stat:
#     path: "{{ nifi_registry_dir }}/bootstrapped"
#   register: p

# - name: Bootstrap nifi
#   include_tasks: bootstrap.yml
#   when: not p.stat.exists

- name: Start nifi registry
  shell: "docker-compose -f {{ nifi_registry_dir }}/docker-compose.yml up -d --force-recreate"
  become: true
  become_user: "{{ nifi_registry_user }}"
